logging:
  level:
    root: INFO
    
server:
  context-path: /
  port: 8111

#数据库版本管理
flyway:
  enabled: true
  table: DEMO_SCHEMA_VERSION


spring:
  datasource:
    #JDBC-H2
    #url: jdbc:h2:file:./dadi-db
    #username: sa
    #password: sa
    driver-class-name: org.h2.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池配置,下面配置说明请参考Druid Github Wiki，配置_DruidDataSource参考配置
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 10
      min-evictable-idle-time-millis: 100000
      validation-query: select 1
      ######Druid监控配置######
      #下面配置说明请参考Druid Github Wiki，配置_配置WebStatFilter
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      #下面配置说明请参考Druid Github Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        #login-username: druid
        #login-password: druid


#mybatis相关配置
mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
